openapi: 3.0.0
info:
  title: SIXT - Xfleet
  description: REST API available to login users to Xfleet
  version: 1.0.0
servers:
  - url: https://{instance_url}/services/apexrest/Xfleet/v1
    variables:
      instance_url:
        description: The base URL for the instance, obtained from the login response
        default: sixtdk.my.salesforce.com
tags:
  - name: Vehicle
    description: To query, create and update Vehicle in Xfleet.
  - name: InvoiceRequest
    description: Invoice Request API
paths:
  /Vehicle:
    post:
      tags:
        - Vehicle
      summary: create a vehicle
      description: Creates vehicle in Xfleet.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                vehicle:
                  $ref: '#/components/schemas/VehicleCreate'
              required:
                - vehicle
      responses:
        '201':
          description: Created
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleResponse'
        '400': 
          description: Bad request, parsing error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '422': 
          description: DML exception
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorMessage: "Insert failed. First exception on row 0; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, NCAP: bad value for restricted picklist field: _5: [NCAP__c]"
        '500': 
          description: Unexpected error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /Vehicle/{vehicleId}:
    patch:
      tags:
        - Vehicle
      summary: update a vehicle
      description: update different parameters on the vehicle
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                vehicle:
                  $ref: '#/components/schemas/Vehicle'
              required:
                - vehicle
            example: 
              vehicle:
                brandName: "Volvo"
                modelName: "XC60"
                tankSize: 61
                consumptionKmPerLiter: 5.1
      parameters:
        - name: vehicleId
          in: path
          schema:
            type: string
          required: true
          example: a0AAO000000IjWB2B0
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleResponse'
        '400': 
          description: Bad request, parsing error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '404': 
          description: Vehicle not found
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorMessage: "List has no rows for assignment to SObject"
        '422': 
          description: DML exception
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorMessage: "Update failed. First exception on row 0 with id a0A0Q000003FoGaUAK; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, NCAP: bad value for restricted picklist field: _5: [NCAP__c]"
        '500': 
          description: Unexpected error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorMessage: "Internal error"
    get:
      tags:
        - Vehicle
      summary: query a vehicle
      description: >-
        Get operation on single Vehicle record in Xfleet. Return all fields that
        are viewable by the API user.
      parameters:
        - name: vehicleId
          in: path
          schema:
            type: string
          required: true
          example: a0AAO000000IjWB2B0
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400': 
          description: Bad request, parsing error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
        '404': 
          description: Vehicle not found
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorMessage: "List has no rows for assignment to SObject"
        '500': 
          description: Unexpected error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /InvoiceRequest:
    post:
      tags:
        - InvoiceRequest
      summary: create Invoice Request
      description: Creates invoice request in Xfleet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                invoiceRequest:
                  $ref: '#/components/schemas/InvoiceRequest'
              required:
                - invoiceRequest
      responses:
        '201':
          description: Created
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceRequestResponse'
        '400': 
          description: Bad request, parsing error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message : "Unknown field: REST_XfleetVehicle.VehicleWrapper.brandNsame at [line:3, column:20]"
                errorCode : "JSON_PARSER_ERROR"
        '404': 
          description: Bad request, parsing error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorMessage: "List has no rows for assignment to SObject"
        '422': 
          description: DML exception
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorMessage: "Update failed. First exception on row 0 with id a0A0Q000003FoGaUAK; first error: INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST, NCAP: bad value for restricted picklist field: _5: [NCAP__c]"
        '424': 
          description: Navision request failed
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errorMessage: "Resource not found in Navision!"
        '500': 
          description: Unexpected error
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Vehicle:
      type: object
      properties:
        acrissCode:
          type: string
          description: ACRISS code
          example: FWAR
        airbagsNumber:
          type: integer
          description: number of airbags
          example: 6
        automaticGears:
          type: boolean
        batteryCapacity:
          type: integer
          example: 1180  
        bluetooth:
          type: boolean
        brandName:
          type: string
          enum:
            - Alfa Romeo
            - Audi
            - BMW
            - Citroën
            - Cupra
            - DS
            - Ferrari
            - Fiat
            - Ford
            - Honda
            - Hyundai
            - Isuzu
            - Jaguar
            - Jeep
            - Kia
            - Land Rover
            - Lexus
            - Mazda
            - Mercedes-Benz
            - MG
            - Mitsubishi
            - Nissan
            - Opel
            - Peugeot
            - Polestar
            - Porsche
            - Renault
            - Seat
            - Skoda
            - Suzuki
            - Tesla
            - Toyota
            - Volvo
            - VW
        buyerAccountName:
          type: string
          example: IKKE SOLG - BILSALG
        carRemarks:
          type: string
          maxLength: 1500
          example: Denne har vinterdæk, skal have skiftet til sommerdæk. /OH
        co2Emissions:
          type: integer
          maximum: 9999
          example: 95
        colorName:
          type: string
          maxLength: 100
          example: red
        consumptionKmPerLiter:
          type: number
          format: float
          example: 19.6
        cruiseControl:
          type: boolean
        deeplink:
          type: string
          example: >-
            https://sixtbilsalg.dk/bil/LAND-ROVER-Range-Rover-Evoque-PHEV-300-HK-SE-276
        deliveryCostsRetailDKK:
          type: integer
          example: 2000
        equipmentList:
          type: string
          example: >-
            Tonede ruder, Driving assistent, Parking assistent inkl.
            Bakkamera,El-indfoldelige sidespejle
        externalId:
          type: string
          example: h3459hk323
        firstRegistrationDate:
          type: string
          format: date
          example: 2019-10-28
        fuelType:
          type: string
          enum:
            - DI
            - EL
            - HBBP
            - HBD
            - BE
            - HBB
        lastVehicleInspection:
          type: string
          format: date
          example: 2021-02-24
        licensePlateCostsDKK:
          type: integer
          example: 1180
        mileage:
          type: integer
          example: 13724
        modelName:
          type: string
          maxLength: 255
          example: 320d Touring M-Sport
        modelXfleet:
          type: string
          maxLength: 255
          example: 320d Touring M-Sport  350 HPa
        modelYear:
          type: integer
          example: 2020
        navigation:
          type: boolean
        ncap:
          type: string
          enum:
            - '0'
            - '1'
            - '2'
            - '3'
            - '4'
            - '5'
        parkingSensor:
          type: boolean
        range:
          type: integer
          example: 350
        regNo:
          type: string
          maxLength: 18
          example: "DK12345"
        registrationDate:
          type: string
          format: date
          example: 2021-02-26  
        remarketingStatus:
          type: string
          enum:
            - Ready to sell
            - Sold
            - Not sold
        retailPriceDKK:
          type: integer
          example: 135000
        retailSales:
          type: boolean
        seatbeltAlarmsNumber:
          type: integer
          example: 7
        serviceInterval:
          type: string
          maxLength: 255
          example: "3 år /30.000 km."
        status:
          type: string
          enum:
            - Procurement
            - Infleet
            - Operations
            - Defleet
            - Sold
            - Stock Car
          example: Stock Car
        steelPriceDKK:
          type: integer
          example: 115000
        tankSize:
          type: integer
          example: 61
        tireOwnership:
          type: string
          enum:
            - Own
            - Rental
        tireSize:
          type: string
          maxLength: 255
          example: 225/45 for - 255/40 R18 bag
        tireType:
          type: string
          enum:
            - Summer
            - Winter
            - All Season
        vehicleBatchName:
          type: string
          example: 2023-C00123
        vin:
          type: string
          maxLength: 25
          example: WF0YXXTTGGGG12345
    VehicleCreate:
      allOf:
        - $ref: '#/components/schemas/Vehicle'
        - type: object
          required:
            - vin
    VehicleResponse:
      type: object
      properties:
        id:
          type: string
          example: a0AAO000000IjWB2B0
    InvoiceRequest:
      type: object
      required:
        - vehicleId
        - customerPriceDKK
        - registrationFeeDKK
        - externalInvoiceNumber
      properties:
        vehicleId:
          type: string
          minLength: 18
          maxLength: 18
          example: a0AAO000000a32j7B1
        customerPriceDKK:
          type: integer
          example: 222000
        registrationFeeDKK:
          type: integer
          example: 15000
        additionalAccessoriesCostDKK:
          type: integer
          example: 222000
        accessoryDescription:
          type: string
          maxLength: 50
          example: sunroof, Heat-reflecting windscreen
        ownerName:
          type: string
          maxLength: 50
          example: Jens Jensen
        ownerAddressLine1:
          type: string
          maxLength: 50
          example: Kongshøjvej 53
        ownerAddressLine2:
          type: string
          maxLength: 50
          example: c/o Spenser
        ownerPostCode:
          type: string
          maxLength: 50
          example: 1218
        ownerCity:
          type: string
          maxLength: 50
          example: København
        driverName:
          type: string
          maxLength: 50
          example: Martin Jensen
        driverAddressLine1:
          type: string
          maxLength: 50
          example: Kongshøjvej 53
        driverAddressLine2:
          type: string
          maxLength: 50
          example: c/o Spenser
        driverPostCode:
          type: string
          maxLength: 50
          example: 1218
        driverCity:
          type: string
          maxLength: 50
          example: København
        exchangeVehicleId:
          type: string
          minLength: 18
          maxLength: 18
          example: a0AAO000000m11i2AA
        externalInvoiceNumber:
          type: string
          maxLength: 50
          example: D-EW84793243
    InvoiceRequestResponse:
      type: object
      properties:
        id:
          type: string
          example: a0BAO000000IxAS1A0
    ErrorResponse:
      type: object
      properties:
        errorMessage:
          type: string
          example: "value cannot be null"
    ErrorResponse400:
      type: object
      properties:
        message:
          type: string
          example: "Unknown field: REST_XfleetVehicle.VehicleWrapper.brandNsame at [line:3, column:20]"
        errorCode:
          type: string
          example: "JSON_PARSER_ERROR"
security:
  - bearerAuth: []
